//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace history.workflow {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private history.workflow.ResultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public history.workflow.ResultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultCode", Namespace="http://tempuri.org/")]
    public enum ResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryCriteriaBaseOfMyTaskCriteria", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QueryCriteriaBaseOfMyTaskCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.PaginationModel PagingInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.MyTaskCriteria QueryCriteriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public history.workflow.PaginationModel PagingInfo {
            get {
                return this.PagingInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PagingInfoField, value) != true)) {
                    this.PagingInfoField = value;
                    this.RaisePropertyChanged("PagingInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public history.workflow.MyTaskCriteria QueryCriteria {
            get {
                return this.QueryCriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryCriteriaField, value) != true)) {
                    this.QueryCriteriaField = value;
                    this.RaisePropertyChanged("QueryCriteria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaginationModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaginationModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageSizeField;
        
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortFieldField;
        
        private history.workflow.SortOrder SortOrderField;
        
        private int ItemCountField;
        
        private int PageCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SortField {
            get {
                return this.SortFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SortFieldField, value) != true)) {
                    this.SortFieldField = value;
                    this.RaisePropertyChanged("SortField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public history.workflow.SortOrder SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ItemCount {
            get {
                return this.ItemCountField;
            }
            set {
                if ((this.ItemCountField.Equals(value) != true)) {
                    this.ItemCountField = value;
                    this.RaisePropertyChanged("ItemCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int PageCount {
            get {
                return this.PageCountField;
            }
            set {
                if ((this.PageCountField.Equals(value) != true)) {
                    this.PageCountField = value;
                    this.RaisePropertyChanged("PageCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyTaskCriteria", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MyTaskCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.ArrayOfInt OriginatorLoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.ArrayOfInt ProcInstIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.ArrayOfString ProcessCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.DatePeriodModel TaskStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.DatePeriodModel ProcessStartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((this.LoginIdField.Equals(value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public history.workflow.ArrayOfInt OriginatorLoginId {
            get {
                return this.OriginatorLoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginatorLoginIdField, value) != true)) {
                    this.OriginatorLoginIdField = value;
                    this.RaisePropertyChanged("OriginatorLoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public history.workflow.ArrayOfInt ProcInstId {
            get {
                return this.ProcInstIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcInstIdField, value) != true)) {
                    this.ProcInstIdField = value;
                    this.RaisePropertyChanged("ProcInstId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public history.workflow.ArrayOfString ProcessCode {
            get {
                return this.ProcessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessCodeField, value) != true)) {
                    this.ProcessCodeField = value;
                    this.RaisePropertyChanged("ProcessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public history.workflow.DatePeriodModel TaskStartDate {
            get {
                return this.TaskStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskStartDateField, value) != true)) {
                    this.TaskStartDateField = value;
                    this.RaisePropertyChanged("TaskStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public history.workflow.DatePeriodModel ProcessStartDate {
            get {
                return this.ProcessStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessStartDateField, value) != true)) {
                    this.ProcessStartDateField = value;
                    this.RaisePropertyChanged("ProcessStartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortOrder", Namespace="http://tempuri.org/")]
    public enum SortOrder : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ascending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Descending = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatePeriodModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DatePeriodModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> DateFromField;
        
        private System.Nullable<System.DateTime> DateToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryListResultBaseOfMyTaskDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QueryListResultBaseOfMyTaskDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.PaginationModel PagingInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.MyTaskDto[] ResultListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public history.workflow.PaginationModel PagingInfo {
            get {
                return this.PagingInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PagingInfoField, value) != true)) {
                    this.PagingInfoField = value;
                    this.RaisePropertyChanged("PagingInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public history.workflow.MyTaskDto[] ResultList {
            get {
                return this.ResultListField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultListField, value) != true)) {
                    this.ResultListField = value;
                    this.RaisePropertyChanged("ResultList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyTaskDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MyTaskDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProcInstIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        private int OriginatorLoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessCodeField;
        
        private System.DateTime TaskStartDateField;
        
        private System.DateTime ProcessStartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProcInstId {
            get {
                return this.ProcInstIdField;
            }
            set {
                if ((this.ProcInstIdField.Equals(value) != true)) {
                    this.ProcInstIdField = value;
                    this.RaisePropertyChanged("ProcInstId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SN {
            get {
                return this.SNField;
            }
            set {
                if ((object.ReferenceEquals(this.SNField, value) != true)) {
                    this.SNField = value;
                    this.RaisePropertyChanged("SN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int OriginatorLoginId {
            get {
                return this.OriginatorLoginIdField;
            }
            set {
                if ((this.OriginatorLoginIdField.Equals(value) != true)) {
                    this.OriginatorLoginIdField = value;
                    this.RaisePropertyChanged("OriginatorLoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ProcessCode {
            get {
                return this.ProcessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessCodeField, value) != true)) {
                    this.ProcessCodeField = value;
                    this.RaisePropertyChanged("ProcessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime TaskStartDate {
            get {
                return this.TaskStartDateField;
            }
            set {
                if ((this.TaskStartDateField.Equals(value) != true)) {
                    this.TaskStartDateField = value;
                    this.RaisePropertyChanged("TaskStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime ProcessStartDate {
            get {
                return this.ProcessStartDateField;
            }
            set {
                if ((this.ProcessStartDateField.Equals(value) != true)) {
                    this.ProcessStartDateField = value;
                    this.RaisePropertyChanged("ProcessStartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="K2StatusDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class K2StatusDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProcInstIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private history.workflow.ArrayOfInt LoginIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProcInstId {
            get {
                return this.ProcInstIdField;
            }
            set {
                if ((this.ProcInstIdField.Equals(value) != true)) {
                    this.ProcInstIdField = value;
                    this.RaisePropertyChanged("ProcInstId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Activity {
            get {
                return this.ActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityField, value) != true)) {
                    this.ActivityField = value;
                    this.RaisePropertyChanged("Activity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public history.workflow.ArrayOfInt LoginIds {
            get {
                return this.LoginIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdsField, value) != true)) {
                    this.LoginIdsField = value;
                    this.RaisePropertyChanged("LoginIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="K2CommentDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class K2CommentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityNameField;
        
        private System.DateTime AddDateField;
        
        private int CommentIDField;
        
        private int LoginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessCodeField;
        
        private int ProcInstIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ActionTo {
            get {
                return this.ActionToField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionToField, value) != true)) {
                    this.ActionToField = value;
                    this.RaisePropertyChanged("ActionTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ActivityName {
            get {
                return this.ActivityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityNameField, value) != true)) {
                    this.ActivityNameField = value;
                    this.RaisePropertyChanged("ActivityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime AddDate {
            get {
                return this.AddDateField;
            }
            set {
                if ((this.AddDateField.Equals(value) != true)) {
                    this.AddDateField = value;
                    this.RaisePropertyChanged("AddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CommentID {
            get {
                return this.CommentIDField;
            }
            set {
                if ((this.CommentIDField.Equals(value) != true)) {
                    this.CommentIDField = value;
                    this.RaisePropertyChanged("CommentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProcessCode {
            get {
                return this.ProcessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessCodeField, value) != true)) {
                    this.ProcessCodeField = value;
                    this.RaisePropertyChanged("ProcessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int ProcInstID {
            get {
                return this.ProcInstIDField;
            }
            set {
                if ((this.ProcInstIDField.Equals(value) != true)) {
                    this.ProcInstIDField = value;
                    this.RaisePropertyChanged("ProcInstID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string RealName {
            get {
                return this.RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RealNameField, value) != true)) {
                    this.RealNameField = value;
                    this.RaisePropertyChanged("RealName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="workflow.WorkFlowServiceSoap")]
    public interface WorkFlowServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 processCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Start", ReplyAction="*")]
        history.workflow.StartResponse Start(history.workflow.StartRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 processCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Approve", ReplyAction="*")]
        history.workflow.ApproveResponse Approve(history.workflow.ApproveRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvolveTask", ReplyAction="*")]
        history.workflow.InvolveTaskResponse InvolveTask(history.workflow.InvolveTaskRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sn 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReAssignTask", ReplyAction="*")]
        history.workflow.ReAssignTaskResponse ReAssignTask(history.workflow.ReAssignTaskRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 apiKey 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cancel", ReplyAction="*")]
        history.workflow.CancelResponse Cancel(history.workflow.CancelRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 queryPara 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaskList", ReplyAction="*")]
        history.workflow.GetTaskListResponse GetTaskList(history.workflow.GetTaskListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 folio 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProcessStatus", ReplyAction="*")]
        history.workflow.GetProcessStatusResponse GetProcessStatus(history.workflow.GetProcessStatusRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 procInstIds 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProcessComments", ReplyAction="*")]
        history.workflow.GetProcessCommentsResponse GetProcessComments(history.workflow.GetProcessCommentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Start", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.StartRequestBody Body;
        
        public StartRequest() {
        }
        
        public StartRequest(history.workflow.StartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int loginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string objectId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string jsonData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apiKey;
        
        public StartRequestBody() {
        }
        
        public StartRequestBody(string processCode, int loginId, string objectId, string folio, string jsonData, string apiKey) {
            this.processCode = processCode;
            this.loginId = loginId;
            this.objectId = objectId;
            this.folio = folio;
            this.jsonData = jsonData;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartResponse", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.StartResponseBody Body;
        
        public StartResponse() {
        }
        
        public StartResponse(history.workflow.StartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.ResultModel StartResult;
        
        public StartResponseBody() {
        }
        
        public StartResponseBody(history.workflow.ResultModel StartResult) {
            this.StartResult = StartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Approve", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.ApproveRequestBody Body;
        
        public ApproveRequest() {
        }
        
        public ApproveRequest(history.workflow.ApproveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int loginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string actionString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string memo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string jsonData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string apiKey;
        
        public ApproveRequestBody() {
        }
        
        public ApproveRequestBody(string processCode, string sn, int loginId, string actionString, string memo, string jsonData, string apiKey) {
            this.processCode = processCode;
            this.sn = sn;
            this.loginId = loginId;
            this.actionString = actionString;
            this.memo = memo;
            this.jsonData = jsonData;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveResponse", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.ApproveResponseBody Body;
        
        public ApproveResponse() {
        }
        
        public ApproveResponse(history.workflow.ApproveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.ResultModel ApproveResult;
        
        public ApproveResponseBody() {
        }
        
        public ApproveResponseBody(history.workflow.ResultModel ApproveResult) {
            this.ApproveResult = ApproveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvolveTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvolveTask", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.InvolveTaskRequestBody Body;
        
        public InvolveTaskRequest() {
        }
        
        public InvolveTaskRequest(history.workflow.InvolveTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvolveTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int assignFromLoginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string assignFromRealName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int assignToLoginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string assignToRealName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apiKey;
        
        public InvolveTaskRequestBody() {
        }
        
        public InvolveTaskRequestBody(string sn, int assignFromLoginId, string assignFromRealName, int assignToLoginId, string assignToRealName, string apiKey) {
            this.sn = sn;
            this.assignFromLoginId = assignFromLoginId;
            this.assignFromRealName = assignFromRealName;
            this.assignToLoginId = assignToLoginId;
            this.assignToRealName = assignToRealName;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvolveTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvolveTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.InvolveTaskResponseBody Body;
        
        public InvolveTaskResponse() {
        }
        
        public InvolveTaskResponse(history.workflow.InvolveTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvolveTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.ResultModel InvolveTaskResult;
        
        public InvolveTaskResponseBody() {
        }
        
        public InvolveTaskResponseBody(history.workflow.ResultModel InvolveTaskResult) {
            this.InvolveTaskResult = InvolveTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReAssignTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReAssignTask", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.ReAssignTaskRequestBody Body;
        
        public ReAssignTaskRequest() {
        }
        
        public ReAssignTaskRequest(history.workflow.ReAssignTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReAssignTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int assignFromLoginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string assignFromRealName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int assignToLoginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string assignToRealName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isAddLog;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string apiKey;
        
        public ReAssignTaskRequestBody() {
        }
        
        public ReAssignTaskRequestBody(string sn, int assignFromLoginId, string assignFromRealName, int assignToLoginId, string assignToRealName, bool isAddLog, string apiKey) {
            this.sn = sn;
            this.assignFromLoginId = assignFromLoginId;
            this.assignFromRealName = assignFromRealName;
            this.assignToLoginId = assignToLoginId;
            this.assignToRealName = assignToRealName;
            this.isAddLog = isAddLog;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReAssignTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReAssignTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.ReAssignTaskResponseBody Body;
        
        public ReAssignTaskResponse() {
        }
        
        public ReAssignTaskResponse(history.workflow.ReAssignTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReAssignTaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.ResultModel ReAssignTaskResult;
        
        public ReAssignTaskResponseBody() {
        }
        
        public ReAssignTaskResponseBody(history.workflow.ResultModel ReAssignTaskResult) {
            this.ReAssignTaskResult = ReAssignTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cancel", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.CancelRequestBody Body;
        
        public CancelRequest() {
        }
        
        public CancelRequest(history.workflow.CancelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int procInstId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apiKey;
        
        public CancelRequestBody() {
        }
        
        public CancelRequestBody(int procInstId, string apiKey) {
            this.procInstId = procInstId;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelResponse", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.CancelResponseBody Body;
        
        public CancelResponse() {
        }
        
        public CancelResponse(history.workflow.CancelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.ResultModel CancelResult;
        
        public CancelResponseBody() {
        }
        
        public CancelResponseBody(history.workflow.ResultModel CancelResult) {
            this.CancelResult = CancelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaskListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaskList", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.GetTaskListRequestBody Body;
        
        public GetTaskListRequest() {
        }
        
        public GetTaskListRequest(history.workflow.GetTaskListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaskListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.QueryCriteriaBaseOfMyTaskCriteria queryPara;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apiKey;
        
        public GetTaskListRequestBody() {
        }
        
        public GetTaskListRequestBody(history.workflow.QueryCriteriaBaseOfMyTaskCriteria queryPara, string apiKey) {
            this.queryPara = queryPara;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaskListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaskListResponse", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.GetTaskListResponseBody Body;
        
        public GetTaskListResponse() {
        }
        
        public GetTaskListResponse(history.workflow.GetTaskListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaskListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.QueryListResultBaseOfMyTaskDto GetTaskListResult;
        
        public GetTaskListResponseBody() {
        }
        
        public GetTaskListResponseBody(history.workflow.QueryListResultBaseOfMyTaskDto GetTaskListResult) {
            this.GetTaskListResult = GetTaskListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessStatus", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.GetProcessStatusRequestBody Body;
        
        public GetProcessStatusRequest() {
        }
        
        public GetProcessStatusRequest(history.workflow.GetProcessStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProcessStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int procInstId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string folio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apiKey;
        
        public GetProcessStatusRequestBody() {
        }
        
        public GetProcessStatusRequestBody(int procInstId, string folio, string apiKey) {
            this.procInstId = procInstId;
            this.folio = folio;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.GetProcessStatusResponseBody Body;
        
        public GetProcessStatusResponse() {
        }
        
        public GetProcessStatusResponse(history.workflow.GetProcessStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProcessStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.K2StatusDto[] GetProcessStatusResult;
        
        public GetProcessStatusResponseBody() {
        }
        
        public GetProcessStatusResponseBody(history.workflow.K2StatusDto[] GetProcessStatusResult) {
            this.GetProcessStatusResult = GetProcessStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessComments", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.GetProcessCommentsRequestBody Body;
        
        public GetProcessCommentsRequest() {
        }
        
        public GetProcessCommentsRequest(history.workflow.GetProcessCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProcessCommentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.ArrayOfInt procInstIds;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apiKey;
        
        public GetProcessCommentsRequestBody() {
        }
        
        public GetProcessCommentsRequestBody(history.workflow.ArrayOfInt procInstIds, string apiKey) {
            this.procInstIds = procInstIds;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcessCommentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public history.workflow.GetProcessCommentsResponseBody Body;
        
        public GetProcessCommentsResponse() {
        }
        
        public GetProcessCommentsResponse(history.workflow.GetProcessCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProcessCommentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public history.workflow.K2CommentDto[] GetProcessCommentsResult;
        
        public GetProcessCommentsResponseBody() {
        }
        
        public GetProcessCommentsResponseBody(history.workflow.K2CommentDto[] GetProcessCommentsResult) {
            this.GetProcessCommentsResult = GetProcessCommentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorkFlowServiceSoapChannel : history.workflow.WorkFlowServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkFlowServiceSoapClient : System.ServiceModel.ClientBase<history.workflow.WorkFlowServiceSoap>, history.workflow.WorkFlowServiceSoap {
        
        public WorkFlowServiceSoapClient() {
        }
        
        public WorkFlowServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkFlowServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        history.workflow.StartResponse history.workflow.WorkFlowServiceSoap.Start(history.workflow.StartRequest request) {
            return base.Channel.Start(request);
        }
        
        public history.workflow.ResultModel Start(string processCode, int loginId, string objectId, string folio, string jsonData, string apiKey) {
            history.workflow.StartRequest inValue = new history.workflow.StartRequest();
            inValue.Body = new history.workflow.StartRequestBody();
            inValue.Body.processCode = processCode;
            inValue.Body.loginId = loginId;
            inValue.Body.objectId = objectId;
            inValue.Body.folio = folio;
            inValue.Body.jsonData = jsonData;
            inValue.Body.apiKey = apiKey;
            history.workflow.StartResponse retVal = ((history.workflow.WorkFlowServiceSoap)(this)).Start(inValue);
            return retVal.Body.StartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        history.workflow.ApproveResponse history.workflow.WorkFlowServiceSoap.Approve(history.workflow.ApproveRequest request) {
            return base.Channel.Approve(request);
        }
        
        public history.workflow.ResultModel Approve(string processCode, string sn, int loginId, string actionString, string memo, string jsonData, string apiKey) {
            history.workflow.ApproveRequest inValue = new history.workflow.ApproveRequest();
            inValue.Body = new history.workflow.ApproveRequestBody();
            inValue.Body.processCode = processCode;
            inValue.Body.sn = sn;
            inValue.Body.loginId = loginId;
            inValue.Body.actionString = actionString;
            inValue.Body.memo = memo;
            inValue.Body.jsonData = jsonData;
            inValue.Body.apiKey = apiKey;
            history.workflow.ApproveResponse retVal = ((history.workflow.WorkFlowServiceSoap)(this)).Approve(inValue);
            return retVal.Body.ApproveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        history.workflow.InvolveTaskResponse history.workflow.WorkFlowServiceSoap.InvolveTask(history.workflow.InvolveTaskRequest request) {
            return base.Channel.InvolveTask(request);
        }
        
        public history.workflow.ResultModel InvolveTask(string sn, int assignFromLoginId, string assignFromRealName, int assignToLoginId, string assignToRealName, string apiKey) {
            history.workflow.InvolveTaskRequest inValue = new history.workflow.InvolveTaskRequest();
            inValue.Body = new history.workflow.InvolveTaskRequestBody();
            inValue.Body.sn = sn;
            inValue.Body.assignFromLoginId = assignFromLoginId;
            inValue.Body.assignFromRealName = assignFromRealName;
            inValue.Body.assignToLoginId = assignToLoginId;
            inValue.Body.assignToRealName = assignToRealName;
            inValue.Body.apiKey = apiKey;
            history.workflow.InvolveTaskResponse retVal = ((history.workflow.WorkFlowServiceSoap)(this)).InvolveTask(inValue);
            return retVal.Body.InvolveTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        history.workflow.ReAssignTaskResponse history.workflow.WorkFlowServiceSoap.ReAssignTask(history.workflow.ReAssignTaskRequest request) {
            return base.Channel.ReAssignTask(request);
        }
        
        public history.workflow.ResultModel ReAssignTask(string sn, int assignFromLoginId, string assignFromRealName, int assignToLoginId, string assignToRealName, bool isAddLog, string apiKey) {
            history.workflow.ReAssignTaskRequest inValue = new history.workflow.ReAssignTaskRequest();
            inValue.Body = new history.workflow.ReAssignTaskRequestBody();
            inValue.Body.sn = sn;
            inValue.Body.assignFromLoginId = assignFromLoginId;
            inValue.Body.assignFromRealName = assignFromRealName;
            inValue.Body.assignToLoginId = assignToLoginId;
            inValue.Body.assignToRealName = assignToRealName;
            inValue.Body.isAddLog = isAddLog;
            inValue.Body.apiKey = apiKey;
            history.workflow.ReAssignTaskResponse retVal = ((history.workflow.WorkFlowServiceSoap)(this)).ReAssignTask(inValue);
            return retVal.Body.ReAssignTaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        history.workflow.CancelResponse history.workflow.WorkFlowServiceSoap.Cancel(history.workflow.CancelRequest request) {
            return base.Channel.Cancel(request);
        }
        
        public history.workflow.ResultModel Cancel(int procInstId, string apiKey) {
            history.workflow.CancelRequest inValue = new history.workflow.CancelRequest();
            inValue.Body = new history.workflow.CancelRequestBody();
            inValue.Body.procInstId = procInstId;
            inValue.Body.apiKey = apiKey;
            history.workflow.CancelResponse retVal = ((history.workflow.WorkFlowServiceSoap)(this)).Cancel(inValue);
            return retVal.Body.CancelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        history.workflow.GetTaskListResponse history.workflow.WorkFlowServiceSoap.GetTaskList(history.workflow.GetTaskListRequest request) {
            return base.Channel.GetTaskList(request);
        }
        
        public history.workflow.QueryListResultBaseOfMyTaskDto GetTaskList(history.workflow.QueryCriteriaBaseOfMyTaskCriteria queryPara, string apiKey) {
            history.workflow.GetTaskListRequest inValue = new history.workflow.GetTaskListRequest();
            inValue.Body = new history.workflow.GetTaskListRequestBody();
            inValue.Body.queryPara = queryPara;
            inValue.Body.apiKey = apiKey;
            history.workflow.GetTaskListResponse retVal = ((history.workflow.WorkFlowServiceSoap)(this)).GetTaskList(inValue);
            return retVal.Body.GetTaskListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        history.workflow.GetProcessStatusResponse history.workflow.WorkFlowServiceSoap.GetProcessStatus(history.workflow.GetProcessStatusRequest request) {
            return base.Channel.GetProcessStatus(request);
        }
        
        public history.workflow.K2StatusDto[] GetProcessStatus(int procInstId, string folio, string apiKey) {
            history.workflow.GetProcessStatusRequest inValue = new history.workflow.GetProcessStatusRequest();
            inValue.Body = new history.workflow.GetProcessStatusRequestBody();
            inValue.Body.procInstId = procInstId;
            inValue.Body.folio = folio;
            inValue.Body.apiKey = apiKey;
            history.workflow.GetProcessStatusResponse retVal = ((history.workflow.WorkFlowServiceSoap)(this)).GetProcessStatus(inValue);
            return retVal.Body.GetProcessStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        history.workflow.GetProcessCommentsResponse history.workflow.WorkFlowServiceSoap.GetProcessComments(history.workflow.GetProcessCommentsRequest request) {
            return base.Channel.GetProcessComments(request);
        }
        
        public history.workflow.K2CommentDto[] GetProcessComments(history.workflow.ArrayOfInt procInstIds, string apiKey) {
            history.workflow.GetProcessCommentsRequest inValue = new history.workflow.GetProcessCommentsRequest();
            inValue.Body = new history.workflow.GetProcessCommentsRequestBody();
            inValue.Body.procInstIds = procInstIds;
            inValue.Body.apiKey = apiKey;
            history.workflow.GetProcessCommentsResponse retVal = ((history.workflow.WorkFlowServiceSoap)(this)).GetProcessComments(inValue);
            return retVal.Body.GetProcessCommentsResult;
        }
    }
}
